# Generated by Django 5.0.1 on 2024-03-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='relase_date',
            new_name='release_date',
        ),
    ]
